### ISSUE TITLE
SureHA Startup issue

### ISSUE THREAD

**Issue by crgreenwood** [benleb/surepetcare#12]
Hi Ben,

I'm getting a failure to start SureHA on Home Assistant startup. Here's the trace:

Logger: homeassistant.config_entries
Source: custom_components/sureha/__init__.py:92
Integration: SureHA (documentation, issues)
First occurred: 8:09:59 PM (1 occurrences)
Last logged: 8:09:59 PM
Error setting up entry Sure Petcare for sureha
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sureha/__init__.py", line 74, in async_setup_entry
    return await spc.async_setup()
  File "/config/custom_components/sureha/__init__.py", line 123, in async_setup
    await self.async_update()
  File "/config/custom_components/sureha/__init__.py", line 92, in async_update
    self.states = await self.surepy.get_entities(refresh=True)
  File "/usr/local/lib/python3.9/site-packages/surepy/__init__.py", line 366, in get_entities
    await self.get_latest_anonymous_drinks(household_id=household_id)
  File "/usr/local/lib/python3.9/site-packages/surepy/__init__.py", line 220, in get_latest_anonymous_drinks
    device_id = felaqua_related_entries[0]["weights"][0]["device_id"]
IndexError: list index out of range
```

We have one catflap, one feeder and one felaqua - happy to get any more data that you need to determine the issue.

**Comment by crgreenwood** [comment]
Update - I've removed the felaqua from the system based on the above and it now sets up correctly.

**Comment by benleb** [comment]
ah thanks! and very interesting fix... 🤨

the current dev branch should also fix this :) so I am closing here....
