### ISSUE TITLE
Integration broken wont set up anymore

### ISSUE THREAD

**Issue by blair287** [benleb/surepetcare#16]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/sureha/__init__.py:95
Integration: SureHA (documentation, issues)
First occurred: 23:31:28 (1 occurrences)
Last logged: 23:31:28

Error setting up entry Sure Petcare for sureha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/sureha/__init__.py", line 75, in async_setup_entry
    return await spc.async_setup()
  File "/config/custom_components/sureha/__init__.py", line 129, in async_setup
    await self.async_update()
  File "/config/custom_components/sureha/__init__.py", line 95, in async_update
    self.states = await self.surepy.get_entities(refresh=True)
  File "/usr/local/lib/python3.9/site-packages/surepy/__init__.py", line 365, in get_entities
    await self.get_latest_anonymous_drinks(household_id=household_id)
  File "/usr/local/lib/python3.9/site-packages/surepy/__init__.py", line 219, in get_latest_anonymous_drinks
    device_id = felaqua_related_entries[0]["weights"][0]["device_id"]
IndexError: list index out of range

**Comment by crgreenwood** [comment]
@blair287 this looks like a duplicate of issue #12 that I reported some time ago. I have not had the time to investigate any further but since removing the Felaqua from the system solved this for me I think it must be related to something that is reported by the Felaqua.

**Comment by benleb** [comment]
@blair287 please try the code I pushed to the dev branch yesterday and change your felaqua batteries before please ;)

**Comment by blair287** [comment]
Working after update and battery change
