### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by Knobiwahn** [benleb/surepetcare#37]
hi any ideas with this error?

Logger: homeassistant.components.surepetcare
Source: components/surepetcare/__init__.py:190
Integration: Sure Petcare ([documentation](https://www.home-assistant.io/integrations/surepetcare), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+surepetcare%22))
First occurred: 18:50:30 (3 occurrences)
Last logged: 18:50:48

Unexpected error fetching surepetcare data: object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/surepetcare/__init__.py", line 190, in _async_update_data
    return await self.surepy.get_entities(refresh=True)
  File "/usr/local/lib/python3.10/site-packages/surepy/__init__.py", line 400, in get_entities
    await self.get_latest_anonymous_drinks(household_id=household_id)
  File "/usr/local/lib/python3.10/site-packages/surepy/__init__.py", line 216, in get_latest_anonymous_drinks
    household_timeline = await self.get_household_timeline(household_id, entries=50)
  File "/usr/local/lib/python3.10/site-packages/surepy/__init__.py", line 266, in get_household_timeline
    if timeline := await self.sac.call(method="GET", resource=resource):
  File "/usr/local/lib/python3.10/site-packages/surepy/client.py", line 281, in call
    responselen = len(response_data.get("data", 0))
TypeError: object of type 'int' has no len()

**Comment by barisahmet** [comment]
Same here.

```
2023-08-17 17:28:11.512 ERROR (MainThread) [custom_components.sureha] Unexpected error fetching sureha_sensors data: object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sureha/__init__.py", line 98, in async_update_data
    return await spc.surepy.get_entities(refresh=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/surepy/__init__.py", line 400, in get_entities
    await self.get_latest_anonymous_drinks(household_id=household_id)
  File "/usr/local/lib/python3.11/site-packages/surepy/__init__.py", line 216, in get_latest_anonymous_drinks
    household_timeline = await self.get_household_timeline(household_id, entries=50)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/surepy/__init__.py", line 266, in get_household_timeline
    if timeline := await self.sac.call(method="GET", resource=resource):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/surepy/client.py", line 281, in call
    responselen = len(response_data.get("data", 0))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()

```

**Comment by gracar2002** [comment]
+1

**Comment by ChristophCaina** [comment]
should be fixed with #59 (new surepy libary version)

**Comment by R3inoudR** [comment]
Any updates about this issue?. Still recieving this error:

```
Unexpected error fetching sureha_sensors data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sureha/__init__.py", line 112, in async_update_data
    return await spc.surepy.get_entities(refresh=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/surepy/__init__.py", line 400, in get_entities
    await self.get_latest_anonymous_drinks(household_id=household_id)
  File "/usr/local/lib/python3.12/site-packages/surepy/__init__.py", line 216, in get_latest_anonymous_drinks
    household_timeline = await self.get_household_timeline(household_id, entries=50)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/surepy/__init__.py", line 266, in get_household_timeline
    if timeline := await self.sac.call(method="GET", resource=resource):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/surepy/client.py", line 286, in call
    responselen = len(response_data.get("data", 0))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
```

**Comment by lp55** [comment]
Hi. The issue is due to a issue on Surepy [here](https://github.com/benleb/surepy/blob/980678524efe57ae7935417dd11578b94751afa4/surepy/client.py#L286) which can be fixed by changing it to this:

`responselen = len(response_data.get("data", []))`

I can create a PR, but will it get looked at? There are quite a few PRs for surepy and it seems to be unmaintained. Can anyone confirm that?

**Comment by ChristophCaina** [comment]
I think, submitting a PR would be great, even if it seems to be unmaintained at the moment.
Maybe, it will be merged at some point. ...

@benleb : are you still maintaining the project?
Or would you allow the community to continue maintenance?

**Comment by lp55** [comment]
Created the [PR](https://github.com/benleb/surepy/pull/219)

**Comment by benleb** [comment]
> [@benleb](https://github.com/benleb) : are you still maintaining the project?

hey! yes, but currently not as active as in the past....

> Or would you allow the community to continue maintenance?

in general I am open to :) what exactly do you have in mind?
  
  
  
@lp55 will care for the PRs latest at the weekend!

**Comment by lp55** [comment]
@benleb if you're open to having more maintainers on this project, I'll be glad to push a few more changes based on what I've been doing in my repos (https://github.com/lp55/sureha/ and https://github.com/lp55/surepy). I got a Felaqua to monitor my pet's water consumption and I've made some improvements on that part, which I felt was missing.

If you could write some guidelines on code quality / structure you expect and data consumption (I don't know if you ever talked directly to Sure PetCare about this), that would help new maintainers and ocasional contributers to know what's expected and keep the code in good quality.

BTW I know I have to document better what I did 😆
