### ISSUE TITLE
Is this integration dead? If not, hereby an issue

### ISSUE THREAD

**Issue by bscheutjens** [benleb/surepetcare#39]
Looking at the reported issues and the lack of communication from the author, this integration seems to be completely dead.

If not, hereby a new issue that is breaking all functionality. Since earlier today I'm getting two errors and the states of my pets aren't updating.  

1)
This error originated from a custom integration.

Logger: surepy
Source: custom_components/sureha/__init__.py:98
Integration: SureHA (documentation, issues)
First occurred: 15:31:18 (53 occurrences)
Last logged: 17:41:18

could not fetch data ¯\_(ツ)_/¯

2)
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/sureha/binary_sensor.py:244
Integration: SureHA (documentation, issues)
First occurred: 15:31:18 (53 occurrences)
Last logged: 17:41:18

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 406, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 211, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/sureha/binary_sensor.py", line 257, in is_on
    return bool(self.extra_state_attributes)
  File "/config/custom_components/sureha/binary_sensor.py", line 244, in extra_state_attributes
    if (device := self._coordinator.data[self._id]) and (
KeyError: 418531

**Comment by PhiHar** [comment]
Same issue with the original HomeAssistant integration. So I tried this one and also not working. The original App still works.

**Comment by PhiHar** [comment]
Please also open in issue in the original Home Assistant Core

**Comment by PhiHar** [comment]
Oh you already did 😂

**Comment by bscheutjens** [comment]
> Oh you already did 😂

Only commented on an issue someone else opened just before me.  But the issues for the official integration also suffer from lack of communication from the author.

**Comment by bscheutjens** [comment]
Lol.. went there to check on that issue and noticed I replied to your issue.. Time to go to bed I guess..

**Comment by PhiHar** [comment]
Official Integration is working again, seems like the surepet servers were the problem. I was able to reinstall again.

**Comment by Tuttle13** [comment]
My integration stopped working, so uninstalled and reinstalled, (SureHA) and after putting in correct details, it goes to a blank screen in HA with just the question mark, X, and close. But it's clearly not logging in.

Also tried the second integration option Sure Petcare to sign in, but after entering details, it instead says "Failed to connect"?

**Comment by netphantm** [comment]
This error originated from a custom integration.

Logger: custom_components.sureha.config_flow
Source: custom_components/sureha/config_flow.py:91
Integration: SureHA (documentation, issues)
First occurred: 07:58:21 (4 occurrences)
Last logged: 08:06:54

Unable to connect to surepetcare.io:

**Comment by blair287** [comment]
> This error originated from a custom integration.
> 
> Logger: custom_components.sureha.config_flow Source: custom_components/sureha/config_flow.py:91 Integration: SureHA (documentation, issues) First occurred: 07:58:21 (4 occurrences) Last logged: 08:06:54
> 
> Unable to connect to surepetcare.io:

I have the exact same error started a day ago with everything unknown I removed integration to add again and get blank box with this error in the log.

**Comment by Djowie** [comment]
Same here :(

**Comment by mbu147** [comment]
+1 :(

**Comment by Alex-ala** [comment]
For reference: This relates to https://github.com/home-assistant/core/issues/93814 and is a problem between surepy (which is a dependency of sureha and surepetcare component).
It seems like surepetcare api is blocking (or at least rate limiting?) requests with a user agent starting with "surepy".
Answer from SurePet outstanding, aswell as a decision on how to work around this. There are temporary workarounds within the discussions of the HA Issue.

**Comment by Tuttle13** [comment]
Somehow, it came back..
